FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y \
    gcc \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Keep the container running for debugging
CMD ["sh", "-c", "sleep infinity"]